permalink: /:title.html

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - publish.sh
  - jekyll_dev.sh

# Publishes posts with a future date
future: false

# Splits your posts up over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10

pygments: true
markdown: redcarpet

title: takidashi
description: "Web dev blog"
keywords: [ruby, rails, coffeescript, nodejs, bdd, скачать бесплатно]
author: england
twitter: https://twitter.com/englandpost
github: https://github.com/england
google: https://plus.google.com/108322217208890073882

tag_page_layout: tag_page
tag_page_dir: tag

comments: true
