permalink: /:title.html

# # Disables custom plugins.
# safe: true

# Enables or disables Jekyll from recreating the site when files are modified.
auto: true

exclude: [README.md, Gemfile, Gemfile.lock, .ruby-version, publish.sh]


# Publishes posts with a future date
future: false

# Splits your posts up over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10

pygments: true
markdown: redcarpet

title: takidashi
description: "Every event is inevitable - if it wasn't, it wouldn't happen"
author: england
twitter: https://twitter.com/englandpost
github: https://github.com/england

tag_page_layout: tag_page
tag_page_dir: tag

comments: true
